packages:
  - 'apis/crud/*'
  - 'apis/games/*'
  - 'apis/portfolio/*'
  - 'apis/vertex/*'

  - 'apps/crud/*'
  - 'apps/games/*'
  - 'apps/portfolio/*'
  - 'apps/local-model/*'

  - 'packages/chain/*'
  - 'packages/game/*'
  - 'packages/games/*'
  - 'packages/games-chains/*'
  - 'packages/games-components/*'
  - 'packages/gen-ai/prompt-builder/*'
  - 'packages/gen-ai/vertex-ai/*'
  - 'packages/media-recorder/*'
  - 'packages/mocks/*'
  - 'packages/models/*'
  - 'packages/password/*'
  - 'packages/prisma/*'
  - 'packages/react-shared/*'
  - 'packages/socket-io/client/*'
  - 'packages/socket-io/server/*'
  - 'packages/types/*'
  - 'packages/utils/*'
