packages:
  - 'apis/*'
  - 'apps/*'
  - 'libs/*'

  - 'apis/crud/*'
  - 'apis/games/*'
  - 'apis/portfolio/*'
  - 'apis/vertex/*'

  - 'libs/chain/*'
  - 'libs/game/*'
  - 'libs/games/*'
  - 'libs/games-chains/*'
  - 'libs/games-components/*'
  - 'libs/gen-ai/*'
  - 'libs/gen-ai/pormpt-builder/*'
  - 'libs/gen-ai/vertex-ai/*'
  - 'libs/media-recorder/*'
  - 'libs/mocks/*'
  - 'libs/models/*'
  - 'libs/password/*'
  - 'libs/prisma/*'
  - 'libs/react-shared/*'
  - 'libs/socket-io/*'
  - 'libs/socket-io/client/*'
  - 'libs/socket-io/server/*'
  - 'libs/types/*'
  - 'libs/utils/*'

  - 'apps/crud/*'
  - 'apps/crud/crud-ui/*'
  - 'apps/games/*'
  - 'apps/games/games-ui/*'
  - 'apps/portfolio/*'
  - 'apps/portfolio/portfolio/*'
  - 'apps/local-model/*'
  - 'apps/local-model/local-model/*'
  - 'apps/wdg-agents/*'
