packages:
  - apps/**
  - packages/**

onlyBuiltDependencies:
  - '@azure/msal-node-extensions'
  - '@azure/msal-node-runtime'
  - '@mui/x-telemetry'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - esbuild
  - keytar
  - nx
  - prisma
  - protobufjs
