services:
  crud-api:
    image: crud-api-db
    ports:
      - '5432:5432'
    volumes:
      - ./src/assets/crud-init.sql:/docker-entrypoint-initb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 10s
      timeout: 5s
      retries: 5
