# Use the official PostgreSQL image with the desired version
FROM postgres:latest

ARG POSTGRES_PASSWORD

# Set environment variables for database configuration
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=aklapper

EXPOSE 5431:5432

# Copy any initialization SQL scripts to the container
COPY db-init.sql /docker-entrypoint-initdb.d/
