name: My Portfolio CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: games-424800
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          service_account: aklapper@games-424800.iam.gserviceaccount.com

      - name: Connect to Cloud SQL
        run: |
          gcloud sql connect games --user=aklapper@games-424800.iam

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Create prisma client for unit tests
      - name: Generate Prisma Client
        run: pnpm generate:test

        # Install Poetry for wdg-agents
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Build PostgreSQL Database Image for games-api & crud-api Unit Tests
      - name: Build PostgreSQL Test Database Image
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: pnpx nx docker-build-db-test games-api --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD}}

      # Start PostgreSQL Test Database Image
      - name: Start PostgreSQL Test Database Container
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: pnpx nx docker-start-db games-api

      # Lint all projects
      - name: Lint all projects
        run: pnpx nx affected -t lint

      # Test all projects
      - name: Test all projects
        env:
          DB_URL_TEST: ${{ secrets.DB_URL_TEST }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          GCS_SERVICE_ACCT_SECRET: ${{ secrets.GCS_SERVICE_ACCT_SECRET }}
        run: pnpx nx affected -t test --exclude=crud-api

        #Build all projects
      - name: Build all Projects
        env:
          DB_URL_TEST: ${{ secrets.DB_URL_TEST }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          GCS_SERVICE_ACCT_SECRET: ${{ secrets.GCS_SERVICE_ACCT_SECRET }}
        run: pnpx nx affected -t build
