name: My Portfolio CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  github_action_ci: ${{ secrets.NX_CLOUD_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm

      # Install Dependencies
      - run: pnpm install --frozen-lockfile

      # Add Nx Cloud Build Cache
      - uses: nrwl/nx-set-shas@v4

        # Install Poetry for wdg-agents
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Setup Python Version for wdg-agents
      - name: Setup Python Version for wdg-agents
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8

      # Install Python app wdg-agents to pass lint
      - name: Install wdg-agents
        run: pnpx nx install wdg-agents

      # Lint all projects
      - name: Lint all projects
        run: pnpx nx affected -t lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm

      # Install Dependencies
      - run: pnpm install --frozen-lockfile

      # Add Nx Cloud Build Cache
      - uses: nrwl/nx-set-shas@v4

      # Install Poetry for wdg-agents
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Setup Python Version for wdg-agents
      - name: Setup Python Version for wdg-agents
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8

      # Install Python app wdg-agents to pass lint and test
      - name: Install wdg-agents
        run: pnpx nx install wdg-agents

      # Create prisma client for unit tests
      - name: Generate Prisma Client
        run: pnpm generate

      # Build Docker Container for API Unit Tests
      - name: Build Docker Container
        run: docker build -f ./Dockerfile.db.testing . -t ci-test

      # Start Docker Container for API Unit Tests
      - name: Start Docker Container
        run: docker compose -f ./docker-compose.yaml up ci-test -d

      # Test all projects
      - name: Test all projects
        env:
          NODE_ENV: testing
          DB_URL_TEST: ${{ secrets.DB_URL_TEST }}
        run: pnpx nx affected -t test

      # Stop Docker Container
      - name: Stop Docker Container
        if: always()
        run: docker compose -f ./docker-compose.yaml down

  build:
    runs-on: ubuntu-latest
    needs: ['lint', 'test']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm

      # Install Dependencies
      - run: pnpm install --frozen-lockfile

      # Add Nx Cloud Build Cache
      - uses: nrwl/nx-set-shas@v4

      # Install Poetry for wdg-agents
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Setup Python Version for wdg-agents
      - name: Setup Python Version for wdg-agents
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8

      # Create prisma client for build
      - name: Generate Prisma Client
        run: pnpm generate

      #Build all projects
      - name: Build all Projects
        env:
          NODE_ENV: production
        run: pnpx nx affected -t build

  typecheck:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      # Install Dependencies
      - run: pnpm install --frozen-lockfile

      # Add Nx Cloud Build Cache
      - uses: nrwl/nx-set-shas@v4

      #Typecheck all projects
      - name: Typecheck all Projects
        run: pnpx nx affected -t typecheck
